//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ETradingSystem.Models
{
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BucketLists = new HashSet<BucketList>();
        }

        public decimal Product_Id { get; set; }
        public Nullable<decimal> Vendor_Id { get; set; }
        [Required(ErrorMessage = "Product Name is required")]
        public string Product_Name { get; set; }
        [Required(ErrorMessage = "Brand is required")]
        public string Brand { get; set; }
        [Required(ErrorMessage = "Color is required")]
        public string Color { get; set; }
        [Required(ErrorMessage = "Price is required")]
        public Nullable<double> Price { get; set; }
        [Required(ErrorMessage = "Available Stock is required")]
        public Nullable<int> Available_Stock { get; set; }
        public string Status { get; set; }
        public string isdeleted { get; set; }
        public string ImageURL { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BucketList> BucketLists { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
