//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ETradingSystem.Models
{
    public partial class Vendor
    {
        [Key]
        public decimal Vendor_Id { get; set; }

        [Required(ErrorMessage = "Vendor Name is required")]
        public string Vendor_Name { get; set; }

        [Required(ErrorMessage = "Vendor Email is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Invalid Email Address")]
        public string Vendor_Email { get; set; }

        [Required(ErrorMessage = "Mobile Number is required")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Invalid Mobile Number")]
        public decimal Mobile_Number { get; set; }

        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Category is required")]
        public string Category { get; set; }

        [Required(ErrorMessage = "Vendor Age is required")]
        [Range(18, 100, ErrorMessage = "Vendor Age must be between 18 and 100")]
        public int Vendor_Age { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters long")]
        public string Passowrd { get; set; }

        [Display(Name = "Hint")]
        public Nullable<int> Hint_Id { get; set; }

        [Display(Name = "Hint Answer")]
        [Required(ErrorMessage = "Hint Answer is required")]
        public string Hint_Answer { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Products = new HashSet<Product>();
        }

        public virtual Hint Hint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
